### ISSUE TITLE
problem in export dialog of shaper difference between STEP and BREP behavior

### ISSUE THREAD

**Issue by otaolafranc** [SalomePlatform/shaper#2]
Hello,
after pointed by an user in the forum, there is an issue with the export dialog of shaper, if we export in brep format we can export from a feature, while if we export in step format this is not possible giving an error (looks like different between linux and windows). the user in windows (can not test it) got “Feature Export has failed during the execution” while I am getting "SIGSEGV 'segmentation violation' detected. address 13." (and will crash salome itself!).
for reproduce this:
1. open shaper
2. create a cylinder with cylinder primitive feature
3. open export dialog
4. try to export file in .STEP format
5. if the Cylinder_1 feature is selected (so we get "all-in-cylinder_1") the export will fail, if the Cylinder_1_1 result is selected (so we get Cylinder_1_1) the exporting will success.
but if we do the same but in step 4. with BREP format, in 5. any of the two selections will succeed.
I imagine that in brep case, if it is a feature it will get its .result() and export that but at least the difference in behavior between the two for simply changing the format is not normal.

**Comment by martin-bernhard** [comment]
The STEPExport method expected the context of the selected shape to be a Result, which is not the case when a feature was selected. Therefore, you could see the SIGSEGV under Linux. Fortunately, the null pointer access was handled on Windows by a generic "catch(...)" and the error message could be displayed.

I created a pull request and am waiting for it to be merged into master.
